context:
  version: "0.5.5"

package:
  name: earthlyls
  version: ${{ version }}

source:
  url: https://github.com/glehmann/earthlyls/archive/${{ version }}.tar.gz
  sha256: 19207937f8c11f0be455a9f46fa6a7bec857a9e7fdec0174f1fd00c153172875

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - earthlyls --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Earthly language server
  homepage: https://github.com/glehmann/earthlyls
  repository: https://github.com/glehmann/earthlyls

extra:
  recipe-maintainers:
    - danielnachun
